### PR TITLE
GRADLE-2075 Fixing tests

### PR DESCRIPTION
**Pull request by besolov**

### CODE REVIEW

**Comment by migue** [comment]
Hey Roman,

Have you closed it on purpose or just by error?

Thx!!

**Comment by besolov** [comment]
@migue , I want to change my email linked with this commit

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by migue** [comment]
Pull request submitted to https://github.com/gradle/gradle/pull/266. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
